export const sampleProducts1 = [
    {
        id: 1,
        imageSource: "/images/sampleProduct/product1.png",
        title: "2 Posters :《FUTURE & PAST》&《THE LAIR》",
        price: 2.40,
        quantity: 500,
        isAvailable: true,
        isAdvertised: false,
    },
    {
        id: 2,
        imageSource: "/images/sampleProduct/product1.png",
        title: "Acrylic Keychain",
        price: 9.000,
        quantity: 200,
        isAvailable: true,
        isAdvertised: false,
    },
]

export const sampleProducts2 = [
    {
        id: 1,
        imageSource: "/images/sampleProduct/product1.png",
        title: "2 Posters :《FUTURE & PAST》&《THE LAIR》",
        price: 2.40,
        quantity: 500,
        isAvailable: true,
        isAdvertised: false,
    },
    {
        id: 2,
        imageSource: "/images/sampleProduct/product1.png",
        title: "Acrylic Keychain",
        price: 9.000,
        quantity: 200,
        isAvailable: true,
        isAdvertised: false,
    },
    {
        id: 3,
        imageSource: "/images/sampleProduct/product1.png",
        title: "Doujin Book 32 pages(R/V) 18 cm x 25,50 cm",
        price: 12.50,
        quantity: 0,
        isAvailable: true,
        isAdvertised: false,
    },
    {
        id: 4,
        imageSource: "/images/sampleProduct/product1.png",
        title: "Enamel Gold Pin",
        price: 3.568,
        quantity: 0,
        isAvailable: true,
        isAdvertised: false,
    },
    {
        id: 5,
        imageSource: "/images/sampleProduct/product1.png",
        title: "Saru Mousepad",
        price: 15.487,
        quantity: 0,
        isAvailable: true,
        isAdvertised: false,
    },
    // {
    //     id: 6,
    //     imageSource: "/images/sampleProduct/product1.png",
    //     title: "Iced Tea 25cl",
    //     price: 3.356,
    //     quantity: 0,
    //     isAvailable: true,
    //     isAdvertised: false,
    // },
    // {
    //     id: 7,
    //     imageSource: "/images/sampleProduct/product1.png",
    //     title: "Frites Paprika",
    //     price: 2.567,
    //     quantity: 0,
    //     isAvailable: true,
    //     isAdvertised: false,
    // },
    // {
    //     id: 8,
    //     imageSource: "/images/sampleProduct/product1.png",
    //     title: "New York Fries",
    //     price: 3.1678,
    //     quantity: 0,
    //     isAvailable: true,
    //     isAdvertised: false,
    // },
    // {
    //     id: 9,
    //     imageSource: "/images/sampleProduct/product1.png",
    //     title: "Crispy Potatoes",
    //     price: 3.7,
    //     quantity: 0,
    //     isAvailable: true,
    //     isAdvertised: false,
    // },
    // {
    //     id: 10,
    //     imageSource: "/images/sampleProduct/product1.png",
    //     title: "Glaces artisanales",
    //     price: 4.678,
    //     quantity: 0,
    //     isAvailable: true,
    //     isAdvertised: false,
    // },
]
