export const sampleProducts1 = [
    {
        id: 1,
        imageSource: "/images/sampleProduct/product1FAT.png",
        title: "2 Posters :《FUTURE & PAST》&《THE LAIR》",
        price_regular: 30.00,
        price_sale: 9.00,
        quantity: 500,
        isAvailable: true,
        isAdvertised: false,
    },
    {
        id: 2,
        imageSource: "/images/sampleProduct/product2FAT.png",
        title: "Acrylic Keychain",
        price_regular: 8.000,
        price_sale: 2.400,
        quantity: 200,
        isAvailable: true,
        isAdvertised: false,
    },
]

export const sampleProducts2 = [
    {
        id: 1,
        imageSource: "/images/sampleProduct/product1FAT.png",
        title: "2 Posters :《FUTURE & PAST》&《THE LAIR》",
        price_regular: 30.00,
        price_sale: 9.00,
        quantity: 500,
        isAvailable: true,
        isAdvertised: false,
    },
    {
        id: 2,
        imageSource: "/images/sampleProduct/product2FAT.png",
        title: "Acrylic Keychain",
        price_regular: 8.000,
        price_sale: 2.400,
        quantity: 200,
        isAvailable: true,
        isAdvertised: false,
    },
    {
        id: 3,
        imageSource: "/images/sampleProduct/product3FAT.png",
        title: "Doujin Book 32 pages(R/V) 18 cm x 25,50 cm",
        price_regular: 25.00,
        price_sale: 12.50,
        quantity: 0,
        isAvailable: true,
        isAdvertised: false,
    },
    {
        id: 4,
        imageSource: "/images/sampleProduct/product4FAT.png",
        title: "Enamel Gold Pin",
        price_regular: 10.00,
        price_sale: 3.000,
        quantity: 0,
        isAvailable: true,
        isAdvertised: false,
    },
    {
        id: 5,
        imageSource: "/images/sampleProduct/product5FAT.png",
        title: "Saru Mousepad",
        price_regular: 29.999,
        price_sale: 15.000,
        quantity: 0,
        isAvailable: true,
        isAdvertised: false,
    },
    // {
    //     id: 6,
    //     imageSource: "/images/sampleProduct/product1FAT.png",
    //     title: "Iced Tea 25cl",
    //     price_regular: 10.00,
    //     price_sale: 3.356,
    //     quantity: 0,
    //     isAvailable: true,
    //     isAdvertised: false,
    // },
    // {
    //     id: 7,
    //     imageSource: "/images/sampleProduct/product1FAT.png",
    //     title: "Frites Paprika",
    //     price_regular: 10.00,
    //     price_sale: 2.567,
    //     quantity: 0,
    //     isAvailable: true,
    //     isAdvertised: false,
    // },
    // {
    //     id: 8,
    //     imageSource: "/images/sampleProduct/product1FAT.png",
    //     title: "New York Fries",
    //     price_regular: 10.00,
    //     price_sale: 3.1678,
    //     quantity: 0,
    //     isAvailable: true,
    //     isAdvertised: false,
    // },
    // {
    //     id: 9,
    //     imageSource: "/images/sampleProduct/product1FAT.png",
    //     title: "Crispy Potatoes",
    //     price_regular: 10.00,
    //     price_sale: 3.7,
    //     quantity: 0,
    //     isAvailable: true,
    //     isAdvertised: false,
    // },
    // {
    //     id: 10,
    //     imageSource: "/images/sampleProduct/product1FAT.png",
    //     title: "Glaces artisanales",
    //     price_regular: 10.00,
    //     price_sale: 4.678,
    //     quantity: 0,
    //     isAvailable: true,
    //     isAdvertised: false,
    // },
]
